# TCL File Generated by Component Editor 22.1
# Fri Jul 21 21:49:23 TRT 2023
# DO NOT MODIFY


# 
# riscv_core "riscv_core" v1.0
#  2023.07.21.21:49:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module riscv_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME riscv_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME riscv_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL riscv_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file riscv_core.sv SYSTEM_VERILOG PATH ../src/rtl/core/riscv_core.sv TOP_LEVEL_FILE
add_fileset_file instr_defs.sv SYSTEM_VERILOG PATH ../src/rtl/include/instr_defs.sv
add_fileset_file param_defs.sv SYSTEM_VERILOG PATH ../src/rtl/include/param_defs.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point altera_axi4_master_1
# 
add_interface altera_axi4_master_1 axi4 start
set_interface_property altera_axi4_master_1 associatedClock clk
set_interface_property altera_axi4_master_1 associatedReset rst
set_interface_property altera_axi4_master_1 readIssuingCapability 1
set_interface_property altera_axi4_master_1 writeIssuingCapability 1
set_interface_property altera_axi4_master_1 combinedIssuingCapability 1
set_interface_property altera_axi4_master_1 ENABLED true
set_interface_property altera_axi4_master_1 EXPORT_OF ""
set_interface_property altera_axi4_master_1 PORT_NAME_MAP ""
set_interface_property altera_axi4_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_master_1 SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_master_1 axi_awid awid Output 1
add_interface_port altera_axi4_master_1 axi_awaddr awaddr Output 32
add_interface_port altera_axi4_master_1 axi_awlen awlen Output 8
add_interface_port altera_axi4_master_1 axi_awsize awsize Output 3
add_interface_port altera_axi4_master_1 axi_awburst awburst Output 2
add_interface_port altera_axi4_master_1 axi_awlock awlock Output 1
add_interface_port altera_axi4_master_1 axi_awcache awcache Output 4
add_interface_port altera_axi4_master_1 axi_awprot awprot Output 3
add_interface_port altera_axi4_master_1 axi_awvalid awvalid Output 1
add_interface_port altera_axi4_master_1 axi_awregion awregion Output 4
add_interface_port altera_axi4_master_1 axi_awqos awqos Output 4
add_interface_port altera_axi4_master_1 axi_awready awready Input 1
add_interface_port altera_axi4_master_1 axi_wdata wdata Output 64
add_interface_port altera_axi4_master_1 axi_wstrb wstrb Output 8
add_interface_port altera_axi4_master_1 axi_wlast wlast Output 1
add_interface_port altera_axi4_master_1 axi_wvalid wvalid Output 1
add_interface_port altera_axi4_master_1 axi_wready wready Input 1
add_interface_port altera_axi4_master_1 axi_bid bid Input 1
add_interface_port altera_axi4_master_1 axi_bresp bresp Input 2
add_interface_port altera_axi4_master_1 axi_bvalid bvalid Input 1
add_interface_port altera_axi4_master_1 axi_bready bready Output 1
add_interface_port altera_axi4_master_1 axi_arid arid Output 1
add_interface_port altera_axi4_master_1 axi_araddr araddr Output 32
add_interface_port altera_axi4_master_1 axi_arlen arlen Output 8
add_interface_port altera_axi4_master_1 axi_arsize arsize Output 3
add_interface_port altera_axi4_master_1 axi_arburst arburst Output 2
add_interface_port altera_axi4_master_1 axi_arlock arlock Output 1
add_interface_port altera_axi4_master_1 axi_arcache arcache Output 4
add_interface_port altera_axi4_master_1 axi_arprot arprot Output 3
add_interface_port altera_axi4_master_1 axi_arvalid arvalid Output 1
add_interface_port altera_axi4_master_1 axi_arqos arqos Output 4
add_interface_port altera_axi4_master_1 axi_arregion arregion Output 4
add_interface_port altera_axi4_master_1 axi_arready arready Input 1
add_interface_port altera_axi4_master_1 axi_rid rid Input 1
add_interface_port altera_axi4_master_1 axi_rdata rdata Input 64
add_interface_port altera_axi4_master_1 axi_rresp rresp Input 2
add_interface_port altera_axi4_master_1 axi_rlast rlast Input 1
add_interface_port altera_axi4_master_1 axi_rvalid rvalid Input 1
add_interface_port altera_axi4_master_1 axi_rready rready Output 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst_n reset_n Input 1

