# TCL File Generated by Component Editor 22.1
# Tue Jul 25 20:15:19 TRT 2023
# DO NOT MODIFY


# 
# riscv_core "riscv_core" v1.0
# Serdar Sayın 2023.07.25.20:15:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module riscv_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME riscv_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Serdar Sayın"
set_module_property DISPLAY_NAME riscv_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL riscv_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file riscv_core.sv SYSTEM_VERILOG PATH ../src/rtl/core/riscv_core.sv TOP_LEVEL_FILE
add_fileset_file instr_defs.sv SYSTEM_VERILOG PATH ../src/rtl/include/instr_defs.sv
add_fileset_file param_defs.sv SYSTEM_VERILOG PATH ../src/rtl/include/param_defs.sv
add_fileset_file reg_file.sv SYSTEM_VERILOG PATH ../src/rtl/core/reg_file.sv
add_fileset_file mem.sv SYSTEM_VERILOG PATH ../src/rtl/core/mem/mem.sv
add_fileset_file ifu.sv SYSTEM_VERILOG PATH ../src/rtl/core/ifu/ifu.sv
add_fileset_file alu.sv SYSTEM_VERILOG PATH ../src/rtl/core/exu/alu.sv
add_fileset_file exu.sv SYSTEM_VERILOG PATH ../src/rtl/core/exu/exu.sv
add_fileset_file id0.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/id0.sv
add_fileset_file id1.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/id1.sv
add_fileset_file riscv_decoder.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder.sv
add_fileset_file riscv_decoder_br.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder_br.sv
add_fileset_file riscv_decoder_ctl_imm.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder_ctl_imm.sv
add_fileset_file riscv_decoder_gpr.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder_gpr.sv
add_fileset_file riscv_decoder_j.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder_j.sv
add_fileset_file riscv_decoder_j_no_rr.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder_j_no_rr.sv
add_fileset_file riscv_decoder_j_no_rr_imm.sv SYSTEM_VERILOG PATH ../src/rtl/core/dec/riscv_decoder_j_no_rr_imm.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point altera_axi4_master_1
# 
add_interface altera_axi4_master_1 axi4 start
set_interface_property altera_axi4_master_1 associatedClock clk
set_interface_property altera_axi4_master_1 associatedReset rst
set_interface_property altera_axi4_master_1 readIssuingCapability 1
set_interface_property altera_axi4_master_1 writeIssuingCapability 1
set_interface_property altera_axi4_master_1 combinedIssuingCapability 1
set_interface_property altera_axi4_master_1 ENABLED true
set_interface_property altera_axi4_master_1 EXPORT_OF ""
set_interface_property altera_axi4_master_1 PORT_NAME_MAP ""
set_interface_property altera_axi4_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_master_1 SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_master_1 axi_awid_f awid Output 1
add_interface_port altera_axi4_master_1 axi_awaddr_f awaddr Output 32
add_interface_port altera_axi4_master_1 axi_awlen_f awlen Output 8
add_interface_port altera_axi4_master_1 axi_awsize_f awsize Output 3
add_interface_port altera_axi4_master_1 axi_awburst_f awburst Output 2
add_interface_port altera_axi4_master_1 axi_awlock_f awlock Output 1
add_interface_port altera_axi4_master_1 axi_awcache_f awcache Output 4
add_interface_port altera_axi4_master_1 axi_awprot_f awprot Output 3
add_interface_port altera_axi4_master_1 axi_awvalid_f awvalid Output 1
add_interface_port altera_axi4_master_1 axi_awregion_f awregion Output 4
add_interface_port altera_axi4_master_1 axi_awqos_f awqos Output 4
add_interface_port altera_axi4_master_1 axi_awready_f awready Input 1
add_interface_port altera_axi4_master_1 axi_wdata_f wdata Output 64
add_interface_port altera_axi4_master_1 axi_wstrb_f wstrb Output 8
add_interface_port altera_axi4_master_1 axi_wlast_f wlast Output 1
add_interface_port altera_axi4_master_1 axi_wvalid_f wvalid Output 1
add_interface_port altera_axi4_master_1 axi_wready_f wready Input 1
add_interface_port altera_axi4_master_1 axi_bid_f bid Input 1
add_interface_port altera_axi4_master_1 axi_bresp_f bresp Input 2
add_interface_port altera_axi4_master_1 axi_bvalid_f bvalid Input 1
add_interface_port altera_axi4_master_1 axi_bready_f bready Output 1
add_interface_port altera_axi4_master_1 axi_arid_f arid Output 1
add_interface_port altera_axi4_master_1 axi_araddr_f araddr Output 32
add_interface_port altera_axi4_master_1 axi_arlen_f arlen Output 8
add_interface_port altera_axi4_master_1 axi_arsize_f arsize Output 3
add_interface_port altera_axi4_master_1 axi_arburst_f arburst Output 2
add_interface_port altera_axi4_master_1 axi_arlock_f arlock Output 1
add_interface_port altera_axi4_master_1 axi_arcache_f arcache Output 4
add_interface_port altera_axi4_master_1 axi_arprot_f arprot Output 3
add_interface_port altera_axi4_master_1 axi_arvalid_f arvalid Output 1
add_interface_port altera_axi4_master_1 axi_arqos_f arqos Output 4
add_interface_port altera_axi4_master_1 axi_arregion_f arregion Output 4
add_interface_port altera_axi4_master_1 axi_arready_f arready Input 1
add_interface_port altera_axi4_master_1 axi_rid_f rid Input 1
add_interface_port altera_axi4_master_1 axi_rdata_f rdata Input 64
add_interface_port altera_axi4_master_1 axi_rresp_f rresp Input 2
add_interface_port altera_axi4_master_1 axi_rlast_f rlast Input 1
add_interface_port altera_axi4_master_1 axi_rvalid_f rvalid Input 1
add_interface_port altera_axi4_master_1 axi_rready_f rready Output 1


# 
# connection point altera_axi4_master_2
# 
add_interface altera_axi4_master_2 axi4 start
set_interface_property altera_axi4_master_2 associatedClock clk
set_interface_property altera_axi4_master_2 associatedReset rst
set_interface_property altera_axi4_master_2 readIssuingCapability 1
set_interface_property altera_axi4_master_2 writeIssuingCapability 1
set_interface_property altera_axi4_master_2 combinedIssuingCapability 1
set_interface_property altera_axi4_master_2 ENABLED true
set_interface_property altera_axi4_master_2 EXPORT_OF ""
set_interface_property altera_axi4_master_2 PORT_NAME_MAP ""
set_interface_property altera_axi4_master_2 CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_master_2 SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_master_2 axi_awid_m awid Output 1
add_interface_port altera_axi4_master_2 axi_awaddr_m awaddr Output 32
add_interface_port altera_axi4_master_2 axi_awlen_m awlen Output 8
add_interface_port altera_axi4_master_2 axi_awsize_m awsize Output 3
add_interface_port altera_axi4_master_2 axi_awburst_m awburst Output 2
add_interface_port altera_axi4_master_2 axi_awlock_m awlock Output 1
add_interface_port altera_axi4_master_2 axi_awcache_m awcache Output 4
add_interface_port altera_axi4_master_2 axi_awprot_m awprot Output 3
add_interface_port altera_axi4_master_2 axi_awvalid_m awvalid Output 1
add_interface_port altera_axi4_master_2 axi_awregion_m awregion Output 4
add_interface_port altera_axi4_master_2 axi_awqos_m awqos Output 4
add_interface_port altera_axi4_master_2 axi_awready_m awready Input 1
add_interface_port altera_axi4_master_2 axi_wdata_m wdata Output 64
add_interface_port altera_axi4_master_2 axi_wstrb_m wstrb Output 8
add_interface_port altera_axi4_master_2 axi_wlast_m wlast Output 1
add_interface_port altera_axi4_master_2 axi_wvalid_m wvalid Output 1
add_interface_port altera_axi4_master_2 axi_wready_m wready Input 1
add_interface_port altera_axi4_master_2 axi_bid_m bid Input 1
add_interface_port altera_axi4_master_2 axi_bresp_m bresp Input 2
add_interface_port altera_axi4_master_2 axi_bvalid_m bvalid Input 1
add_interface_port altera_axi4_master_2 axi_bready_m bready Output 1
add_interface_port altera_axi4_master_2 axi_arid_m arid Output 1
add_interface_port altera_axi4_master_2 axi_araddr_m araddr Output 32
add_interface_port altera_axi4_master_2 axi_arlen_m arlen Output 8
add_interface_port altera_axi4_master_2 axi_arsize_m arsize Output 3
add_interface_port altera_axi4_master_2 axi_arburst_m arburst Output 2
add_interface_port altera_axi4_master_2 axi_arlock_m arlock Output 1
add_interface_port altera_axi4_master_2 axi_arcache_m arcache Output 4
add_interface_port altera_axi4_master_2 axi_arprot_m arprot Output 3
add_interface_port altera_axi4_master_2 axi_arvalid_m arvalid Output 1
add_interface_port altera_axi4_master_2 axi_arqos_m arqos Output 4
add_interface_port altera_axi4_master_2 axi_arregion_m arregion Output 4
add_interface_port altera_axi4_master_2 axi_arready_m arready Input 1
add_interface_port altera_axi4_master_2 axi_rid_m rid Input 1
add_interface_port altera_axi4_master_2 axi_rdata_m rdata Input 64
add_interface_port altera_axi4_master_2 axi_rresp_m rresp Input 2
add_interface_port altera_axi4_master_2 axi_rlast_m rlast Input 1
add_interface_port altera_axi4_master_2 axi_rvalid_m rvalid Input 1
add_interface_port altera_axi4_master_2 axi_rready_m rready Output 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst_n reset_n Input 1

