# SPDX-FileCopyrightText: 2023 Serdar Sayın <https://serdarsayin.com>
#
# SPDX-License-Identifier: Apache-2.0

formal: uart_apb
uart_apb:
	sby -f $(TB_DIR)formal/uart_apb.sby
	sby -f $(TB_DIR)formal/axixbar.sby
